# Generated by Django 3.1.7 on 2021-04-08 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('team_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('team_description', models.CharField(blank=True, default='desc', max_length=500, null=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='free', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, default='new member', max_length=100, null=True)),
                ('member_position', models.CharField(blank=True, default='teammember', max_length=100, null=True)),
                ('joining_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('member_status', models.CharField(blank=True, default='free', max_length=50, null=True)),
                ('member_email', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teams.team')),
            ],
        ),
    ]
