# Generated by Django 3.1.7 on 2021-03-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_status',
            field=models.CharField(blank=True, default='free', max_length=50, null=True),
        ),
    ]
