# Generated by Django 3.1.7 on 2021-04-09 17:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskdata',
            fields=[
                ('task_name', models.CharField(default='newassignment', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('task_details', models.CharField(blank=True, default='newassignment', max_length=30, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('task_status', models.IntegerField(blank=True, default='0', null=True)),
                ('assign_member', models.ForeignKey(default='none', on_delete=django.db.models.deletion.DO_NOTHING, to='teams.member')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_name', models.CharField(default='newproj', max_length=200, primary_key=True, serialize=False, unique=True)),
                ('Proj_description', models.CharField(blank=True, default='description', max_length=500, null=True)),
                ('proj_status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teams.team')),
            ],
        ),
    ]
