# Generated by Django 3.1.7 on 2021-03-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
