# Generated by Django 3.1.7 on 2021-04-08 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_member_member_status'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='assign_member',
            field=models.OneToOneField(default='none', on_delete=django.db.models.deletion.DO_NOTHING, to='teams.member'),
        ),
    ]
