# Generated by Django 3.1.7 on 2021-03-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_member_member_status'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Taskdata',
        ),
    ]
