# Generated by Django 3.1.7 on 2021-04-08 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_member_member_status'),
        ('task', '0002_auto_20210408_1005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taskdata',
            new_name='Task',
        ),
    ]
