# Generated by Django 3.1.7 on 2021-04-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210417_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_status',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
