# Generated by Django 3.1.7 on 2021-03-26 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210326_0928'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Taskdata',
        ),
    ]
