# Generated by Django 3.1.7 on 2021-04-08 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_member_member_status'),
        ('task', '0003_auto_20210408_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assign_member',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.DO_NOTHING, to='teams.member'),
        ),
    ]
