# Generated by Django 3.1.7 on 2021-03-26 04:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_member_member_status'),
        ('task', '0003_delete_taskdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskdata',
            fields=[
                ('task_name', models.CharField(default='newassignment', max_length=30, primary_key=True, serialize=False, unique=True)),
                ('task_details', models.CharField(blank=True, default='newassignment', max_length=30, null=True)),
                ('start_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('task_status', models.CharField(blank=True, default='pending', max_length=30, null=True)),
                ('assign_member', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.DO_NOTHING, to='teams.member')),
            ],
        ),
    ]
